=== raniadammak/tpsoa-jialin-jingjing/tpsoa-jialin-jingjing/tpSOA/src/ex7/commande.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<xsd:schema version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	
	 <xsd:element name="ligne-produit">
  		<xsd:complexType>
   		   <xsd:sequence>
     		 	<xsd:element name="reference-produit" type="xsd:string"/>
     		 	<xsd:element name="quantite" type="xsd:int"/>
     			<xsd:element name="prix" type="xsd:float"/>
   			</xsd:sequence>
  		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="lignes-produit">
  		<xsd:complexType>
   			<xsd:sequence>
     			<xsd:element ref="ligne-produit" maxOccurs="unbounded"/>		
   			</xsd:sequence>
  		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="commande">
    	<xsd:complexType>
     		 <xsd:sequence>
				<xsd:element name="reference" type="xsd:string"/>
				<xsd:element name="date" type="xsd:date"/>
				<xsd:element ref="lignes-produit"/>
     		 </xsd:sequence>
    	</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== raniadammak/tpsoa-jialin-jingjing/trunk/tpsoa-jialin-jingjing/tpSOA/src/ex7/commande.xml
<?xml version="1.0" encoding="UTF-8"?>
<commande 
	xmlns:tns="http://www.leuville.com/commande" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.leuville.com/commande commande.xsd ">
  <reference>CMD0123456789</reference>
  <date>2009-03-02T15:39:00</date>
  <lignes-produit>
    <ligne-produit>
      <reference-produit>P1</reference-produit>
      <quantite>2</quantite>
    </ligne-produit>
     <ligne-produit>
      <reference-produit>P2</reference-produit>
      <quantite>5</quantite>
    </ligne-produit>
  </lignes-produit>
</commande>
